/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kirtasiyeotomati;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emirhan
 */
public class YoneticiEkrani extends javax.swing.JFrame {

    DefaultTableModel tableMusteriModel;
    DefaultTableModel tabloUrunModel;

    public YoneticiEkrani() {
        initComponents();

        tableMusteriModel = new DefaultTableModel();
        tableMusteriModel.setColumnIdentifiers(new Object[]{"ID", "AD SOYAD", "EMAİL"});
        tbl_musteriTablo.setModel(tableMusteriModel);

        tabloUrunModel = new DefaultTableModel();
        tabloUrunModel.setColumnIdentifiers(new Object[]{"ID", "Ürün Adı", "Ürün Fiyat", "Ürün Stok Adet"});
        tbl_urunTablo.setModel(tabloUrunModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_musteriEkle = new javax.swing.JButton();
        btn_musteriSil = new javax.swing.JButton();
        btn_urunEkle = new javax.swing.JButton();
        btn_urunSil = new javax.swing.JButton();
        btn_urunGuncelle = new javax.swing.JButton();
        btn_musteriGuncelle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_urunTablo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_musteriTablo = new javax.swing.JTable();
        btn_urunArama = new javax.swing.JButton();
        btn_musteriArama = new javax.swing.JButton();
        txt_urunArama = new javax.swing.JTextField();
        txt_musteriArama = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_kullaniciKayitEmail = new javax.swing.JTextField();
        txt_kullaniciKayitAdiSoyadi = new javax.swing.JTextField();
        txt_kullaniciKayitSifre = new javax.swing.JTextField();
        chcbox_KullaniciUserTipi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_kullaniciKayitId = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txt_urunAdi = new javax.swing.JTextField();
        txt_urunFiyati = new javax.swing.JTextField();
        txt_urunStokAdedi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_urunId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        menu_bar_anasayfayadon = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_bar_kirtasiyedenCık = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_ıtem_yoneticiDuzenle = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Yönetici", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        btn_musteriEkle.setText("Müşteri Ekle");
        btn_musteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musteriEkleActionPerformed(evt);
            }
        });

        btn_musteriSil.setText("Müşteri Sil");
        btn_musteriSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musteriSilActionPerformed(evt);
            }
        });

        btn_urunEkle.setText("Ürün Ekle");
        btn_urunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urunEkleActionPerformed(evt);
            }
        });

        btn_urunSil.setText("Ürün Sil");
        btn_urunSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urunSilActionPerformed(evt);
            }
        });

        btn_urunGuncelle.setText("Ürün Güncelle");
        btn_urunGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urunGuncelleActionPerformed(evt);
            }
        });

        btn_musteriGuncelle.setText("Müşteri Güncelle");
        btn_musteriGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musteriGuncelleActionPerformed(evt);
            }
        });

        tbl_urunTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_urunTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_urunTablo);

        tbl_musteriTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_musteriTabloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_musteriTablo);

        btn_urunArama.setText("Ürün Arama");
        btn_urunArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urunAramaActionPerformed(evt);
            }
        });

        btn_musteriArama.setText("Müşteri Arama");
        btn_musteriArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musteriAramaActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kullanıcı Kayıt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        chcbox_KullaniciUserTipi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chcbox_KullaniciUserTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Müşteri", "Yönetici", " " }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Email");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Kullanıcı Adı Soyad");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Kullanıcı Şifre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Kullanıcı Tipi");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Kullanıcı Id");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kullaniciKayitId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_kullaniciKayitSifre)
                                        .addComponent(txt_kullaniciKayitAdiSoyadi)
                                        .addComponent(chcbox_KullaniciUserTipi, 0, 200, Short.MAX_VALUE)
                                        .addComponent(txt_kullaniciKayitEmail)))))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kullaniciKayitEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kullaniciKayitAdiSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kullaniciKayitSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chcbox_KullaniciUserTipi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_kullaniciKayitId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ürün Kayıt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Ürün Adı ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Ürün Fiyatı");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Ürün Stok Adedi");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Ürün Id");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_urunId)
                    .addComponent(txt_urunFiyati, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txt_urunAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txt_urunStokAdedi, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_urunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_urunFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_urunStokAdedi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_urunId, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_urunArama, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_urunArama, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_urunEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btn_urunSil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_urunGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(btn_musteriEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_musteriSil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_musteriGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(txt_musteriArama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_musteriArama, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_urunArama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_musteriArama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_urunArama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_musteriArama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_urunGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_urunSil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_urunEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_musteriGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_musteriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_musteriSil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        jMenu1.setText("Çıkış İşlemleri");

        jMenuItem1.setText("Ana Sayfaya Geri Dön");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menu_bar_kirtasiyedenCık.setText("Kırtasiyeden Çık");
        menu_bar_kirtasiyedenCık.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_bar_kirtasiyedenCıkActionPerformed(evt);
            }
        });
        jMenu1.add(menu_bar_kirtasiyedenCık);

        menu_bar_anasayfayadon.add(jMenu1);

        jMenu2.setText("Yönetici İşlemleri");

        menu_ıtem_yoneticiDuzenle.setText("Yönetici Düzenle");
        menu_ıtem_yoneticiDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ıtem_yoneticiDuzenleActionPerformed(evt);
            }
        });
        jMenu2.add(menu_ıtem_yoneticiDuzenle);

        menu_bar_anasayfayadon.add(jMenu2);

        setJMenuBar(menu_bar_anasayfayadon);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_musteriAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musteriAramaActionPerformed

        String search = this.txt_musteriArama.getText();
        tableMusteriModel.setRowCount(0);
        ArrayList<Kullanici> kullaniciList = KirtasiyeDatabase.kullaniciSearch(search);

        for (Kullanici newk : kullaniciList) {
            tableMusteriModel.addRow(new Object[]{newk.kullaniciId, newk.kullaniciadSoyad, newk.kullaniciemail});
        }

        txt_kullaniciKayitAdiSoyadi.setText("");
        txt_kullaniciKayitEmail.setText("");
        txt_kullaniciKayitSifre.setText("");
        chcbox_KullaniciUserTipi.setSelectedIndex(0);


    }//GEN-LAST:event_btn_musteriAramaActionPerformed

    private void tbl_musteriTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_musteriTabloMouseClicked

        if (tbl_musteriTablo.getSelectedRow() < 0) {
            return;
        }
        int id = (int) tableMusteriModel.getValueAt(tbl_musteriTablo.getSelectedRow(), 0);

        Kullanici newk = KirtasiyeDatabase.SearchPersonelById(id);

        if (newk != null) {
            txt_kullaniciKayitId.setText(String.valueOf(newk.kullaniciId));
            txt_kullaniciKayitAdiSoyadi.setText(newk.kullaniciadSoyad);
            txt_kullaniciKayitEmail.setText(newk.kullaniciemail);
            txt_kullaniciKayitSifre.setText(newk.kullanicisifre);

            switch (newk.kullaniciTipi) {
                case "Müşteri":
                    chcbox_KullaniciUserTipi.setSelectedIndex(0);
                    break;
                case "Yönetici":
                    chcbox_KullaniciUserTipi.setSelectedIndex(1);
                    break;
            }

        }


    }//GEN-LAST:event_tbl_musteriTabloMouseClicked

    private void btn_musteriGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musteriGuncelleActionPerformed

        Kullanici newk = new Kullanici();

        newk.kullaniciId = Integer.parseInt(txt_kullaniciKayitId.getText());
        newk.kullaniciadSoyad = txt_kullaniciKayitAdiSoyadi.getText();
        newk.kullaniciemail = txt_kullaniciKayitEmail.getText();
        newk.kullanicisifre = txt_kullaniciKayitSifre.getText();
        newk.kullaniciTipi = chcbox_KullaniciUserTipi.getSelectedItem().toString();

        if (KirtasiyeDatabase.Updatep(newk)) {
            JOptionPane.showMessageDialog(this, "Müşteri Başarıyla Güncellendi");
        } else {
            JOptionPane.showMessageDialog(this, "Müşteri Güncellenmedi");
        }

        txt_kullaniciKayitAdiSoyadi.setText("");
        txt_kullaniciKayitEmail.setText("");
        txt_kullaniciKayitSifre.setText("");
        chcbox_KullaniciUserTipi.setSelectedIndex(0);


    }//GEN-LAST:event_btn_musteriGuncelleActionPerformed

    private void btn_musteriSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musteriSilActionPerformed

        if (tbl_musteriTablo.getSelectedRow() < 0) {
            return;
        }
        int id = (int) tableMusteriModel.getValueAt(tbl_musteriTablo.getSelectedRow(), 0);

        if (KirtasiyeDatabase.Deletep(id)) {
            JOptionPane.showMessageDialog(this, "Müşteri Başarıyla Silindi");
        } else {
            JOptionPane.showMessageDialog(this, "Müşteri Silinmedi");
        }
        txt_kullaniciKayitAdiSoyadi.setText("");
        txt_kullaniciKayitEmail.setText("");
        txt_kullaniciKayitSifre.setText("");


    }//GEN-LAST:event_btn_musteriSilActionPerformed

    private void btn_musteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musteriEkleActionPerformed

        try {

            if (txt_kullaniciKayitAdiSoyadi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lütfen Adınızı Ve Soyadınızı Giriniz");
            } else if (txt_kullaniciKayitEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lütfen Emailinizi Giriniz");
            } else if (txt_kullaniciKayitSifre.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lütfen Şifrenizi Giriniz");
            } else {

                Kullanici newk = new Kullanici();

                newk.kullaniciemail = txt_kullaniciKayitEmail.getText();
                newk.kullaniciadSoyad = txt_kullaniciKayitAdiSoyadi.getText();
                newk.kullanicisifre = txt_kullaniciKayitSifre.getText();
                newk.kullaniciTipi = chcbox_KullaniciUserTipi.getSelectedItem().toString();

                if (KirtasiyeDatabase.Addp(newk)) {
                    JOptionPane.showMessageDialog(this, "Kullanıcı Başarıyla Eklendi");
                } else {
                    JOptionPane.showMessageDialog(this, "Kullanıcı Eklenmedi");
                }

            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btn_musteriEkleActionPerformed

    private void btn_urunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urunEkleActionPerformed

        try {

            if (txt_urunAdi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lütfen Ürünün Adını Giriniz");
            } else if (txt_urunFiyati.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lütfen Ürünün Fiyatını Giriniz");
            } else if (txt_urunStokAdedi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lütfen Ürünün Stok Adedini Giriniz");
            } else {

                Urun urun = new Urun();

                urun.urunAdi = txt_urunAdi.getText();
                urun.urunFiyati = txt_urunFiyati.getText();
                urun.urunStokAdedi = txt_urunStokAdedi.getText();

                if (KirtasiyeDatabase.Addu(urun)) {
                    JOptionPane.showMessageDialog(this, "Ürün Başarıyla Eklendi");
                } else {
                    JOptionPane.showMessageDialog(this, "Ürün Eklenmedi");
                }

            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btn_urunEkleActionPerformed

    private void btn_urunAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urunAramaActionPerformed

        String search = this.txt_urunArama.getText();
        tabloUrunModel.setRowCount(0);
        ArrayList<Urun> urunList = KirtasiyeDatabase.urunSearch(search);

        for (Urun newuUrun : urunList) {
            tabloUrunModel.addRow(new Object[]{newuUrun.urunId, newuUrun.urunAdi, newuUrun.urunFiyati, newuUrun.urunStokAdedi});
        }

        txt_urunFiyati.setText("");
        txt_urunAdi.setText("");
        txt_urunStokAdedi.setText("");
        txt_urunStokAdedi.setText("");

    }//GEN-LAST:event_btn_urunAramaActionPerformed

    private void tbl_urunTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_urunTabloMouseClicked

        if (tbl_urunTablo.getSelectedRow() < 0) {
            return;
        }
        int id = (int) tabloUrunModel.getValueAt(tbl_urunTablo.getSelectedRow(), 0);

        Urun newUrun = KirtasiyeDatabase.SearchUrunById(id);

        if (newUrun != null) {
            txt_urunId.setText(String.valueOf(newUrun.urunId));
            txt_urunAdi.setText(newUrun.urunAdi);
            txt_urunFiyati.setText(newUrun.urunFiyati);
            txt_urunStokAdedi.setText(newUrun.urunStokAdedi);

        }


    }//GEN-LAST:event_tbl_urunTabloMouseClicked

    private void btn_urunSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urunSilActionPerformed
        if (tbl_urunTablo.getSelectedRow() < 0) {
            return;
        }
        int id = (int) tabloUrunModel.getValueAt(tbl_urunTablo.getSelectedRow(), 0);

        if (KirtasiyeDatabase.Deleteu(id)) {
            JOptionPane.showMessageDialog(this, "Ürün Başarıyla Silindi");
        } else {
            JOptionPane.showMessageDialog(this, "Ürün Silinmedi");
        }
        txt_urunAdi.setText("");
        txt_urunFiyati.setText("");
        txt_urunStokAdedi.setText("");

    }//GEN-LAST:event_btn_urunSilActionPerformed

    private void btn_urunGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urunGuncelleActionPerformed

        Urun newUrun = new Urun();

        newUrun.urunId = Integer.parseInt(txt_urunId.getText());
        newUrun.urunAdi = txt_urunAdi.getText();
        newUrun.urunFiyati = txt_urunFiyati.getText();
        newUrun.urunStokAdedi = txt_urunStokAdedi.getText();

        if (KirtasiyeDatabase.UpdateUrun(newUrun)) {
            JOptionPane.showMessageDialog(this, "Ürün Başarıyla Güncellendi");
        } else {
            JOptionPane.showMessageDialog(this, "Ürün Güncellenmedi");
        }

        txt_urunAdi.setText("");
        txt_urunFiyati.setText("");
        txt_urunStokAdedi.setText("");


    }//GEN-LAST:event_btn_urunGuncelleActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AnaEkran anaEkran = new AnaEkran();
        anaEkran.setVisible(true);
        setVisible(false);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menu_bar_kirtasiyedenCıkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_bar_kirtasiyedenCıkActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Çıkmak İstediğinizden Emin Misiniz ?", " Kontrol ", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {

            System.exit(0);
        } else {
            return;
        }


    }//GEN-LAST:event_menu_bar_kirtasiyedenCıkActionPerformed

    private void menu_ıtem_yoneticiDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ıtem_yoneticiDuzenleActionPerformed
        
        
        
        
    }//GEN-LAST:event_menu_ıtem_yoneticiDuzenleActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_musteriArama;
    private javax.swing.JButton btn_musteriEkle;
    private javax.swing.JButton btn_musteriGuncelle;
    private javax.swing.JButton btn_musteriSil;
    private javax.swing.JButton btn_urunArama;
    private javax.swing.JButton btn_urunEkle;
    private javax.swing.JButton btn_urunGuncelle;
    private javax.swing.JButton btn_urunSil;
    private javax.swing.JComboBox<String> chcbox_KullaniciUserTipi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menu_bar_anasayfayadon;
    private javax.swing.JMenuItem menu_bar_kirtasiyedenCık;
    private javax.swing.JMenuItem menu_ıtem_yoneticiDuzenle;
    private javax.swing.JTable tbl_musteriTablo;
    private javax.swing.JTable tbl_urunTablo;
    private javax.swing.JTextField txt_kullaniciKayitAdiSoyadi;
    private javax.swing.JTextField txt_kullaniciKayitEmail;
    private javax.swing.JTextField txt_kullaniciKayitId;
    private javax.swing.JTextField txt_kullaniciKayitSifre;
    private javax.swing.JTextField txt_musteriArama;
    private javax.swing.JTextField txt_urunAdi;
    private javax.swing.JTextField txt_urunArama;
    private javax.swing.JTextField txt_urunFiyati;
    private javax.swing.JTextField txt_urunId;
    private javax.swing.JTextField txt_urunStokAdedi;
    // End of variables declaration//GEN-END:variables
}
